/********************************************************************
* src/Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDict();
extern void G__cpp_setup_inheritanceDict();
extern void G__cpp_setup_typetableDict();
extern void G__cpp_setup_memvarDict();
extern void G__cpp_setup_globalDict();
extern void G__cpp_setup_memfuncDict();
extern void G__cpp_setup_funcDict();
extern void G__set_cpp_environmentDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "src/ActionBase.h"
#include "src/Coordinate.h"
#include "src/Field.h"
#include "src/FieldAction.h"
#include "src/Main.h"
#include "src/Particle.h"
#include "src/ParticleAction.h"
#include "src/PhysicsBase.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DictLN_string;
extern G__linked_taginfo G__DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictLN_lattice;
extern G__linked_taginfo G__DictLN_latticecLcLCoordinate;
extern G__linked_taginfo G__DictLN_latticecLcLPhysicsBase;
extern G__linked_taginfo G__DictLN_maplElatticecLcLCoordinatecOdoublecOlesslElatticecLcLCoordinategRcOallocatorlEpairlEconstsPlatticecLcLCoordinatecOdoublegRsPgRsPgR;
extern G__linked_taginfo G__DictLN_vectorlEmaplElatticecLcLCoordinatecOdoublecOlesslElatticecLcLCoordinategRcOallocatorlEpairlEconstsPlatticecLcLCoordinatecOdoublegRsPgRsPgRcOallocatorlEmaplElatticecLcLCoordinatecOdoublecOlesslElatticecLcLCoordinategRcOallocatorlEpairlEconstsPlatticecLcLCoordinatecOdoublegRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlEmaplElatticecLcLCoordinatecOdoublecOlesslElatticecLcLCoordinategRcOallocatorlEpairlEconstsPlatticecLcLCoordinatecOdoublegRsPgRsPgRcOallocatorlEmaplElatticecLcLCoordinatecOdoublecOlesslElatticecLcLCoordinategRcOallocatorlEpairlEconstsPlatticecLcLCoordinatecOdoublegRsPgRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictLN_latticecLcLActionBase;
extern G__linked_taginfo G__DictLN_maplEstringcOconstsPlatticecLcLActionFactoryStorecLcLFactoryBasemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOconstsPlatticecLcLActionFactoryStorecLcLFactoryBasemUgRsPgRsPgR;
extern G__linked_taginfo G__DictLN_latticecLcLField;
extern G__linked_taginfo G__DictLN_latticecLcLLatticeSimulation;
extern G__linked_taginfo G__DictLN_latticecLcLParticle;

/* STUB derived class for protected member access */
